language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - yarn install
script:
    - yarn build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: dist/
    github-token: $GITHUB_TOKEN
    repo: martynau/deploy
    keep-history: true
    target-branch: master
    on:
        branch: master